### ISSUE TITLE
phusion/baseimage tags are different

### ISSUE THREAD

**Issue by elliotykim** [ctindel/ubiquiti-docker#37]
https://github.com/ctindel/ubiquiti-docker/blob/master/unifi/Dockerfile#L1
https://github.com/ctindel/ubiquiti-docker/blob/master/unifi-video/Dockerfile#L1

You have 2 different tags here. Would be nice if they used the same tag.

**Comment by ctindel** [comment]
Yeah that's because they upgraded to ubuntu 16.04 with 0.9.19 and i just never went through and tested with upgrading to the 16.04 ubuntu debian package (right now unifi-video is using their ubuntu 14.04 package).

https://github.com/phusion/baseimage-docker/releases

**Comment by ctindel** [comment]
OK, I unified these and upgrade the unifi-video code to use Ubuntu 16.04 packages.

**Comment by elliotykim** [comment]
thanks!
