### ISSUE TITLE
remove intermediate containers

### ISSUE THREAD

**Issue by elliotykim** [ctindel/ubiquiti-docker#38]
do you mean `-rm=true` here?

https://github.com/ctindel/ubiquiti-docker/blob/master/unifi/Makefile#L10
https://github.com/ctindel/ubiquiti-docker/blob/master/unifi-video/Makefile#L10

**Comment by ctindel** [comment]
Yes, I did mean to do that.  Nice catch!  

Fixed in https://github.com/ctindel/ubiquiti-docker/pull/41
