### ISSUE TITLE
Please update repository

### ISSUE THREAD

**Issue by x2on** [ctindel/ubiquiti-docker#55]
3.9.7 is already released - please update your repository!

**Comment by kevsterd** [comment]
This repo isnt maintained any longer.....   The consensus on the Unifi VIdeo forums was that https://github.com/pducharme/UniFi-Video-Controller seems the best updated - Docker repo https://hub.docker.com/r/pducharme/unifi-video-controller/   Its what I swapped to and seems to work perfectly well.   See https://community.ubnt.com/t5/UniFi-Video/Running-Unifi-Video-3-1-5-in-Docker-on-Synology/td-p/1573739/page/11
